[package]
name = "image_editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

image = "0.24.3"
buffer = "0.1.9"
rand = "0.8.5"