[package]
name = "image_editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.4"
image_hl = {path = "image_hl"}
image_editor_gui = {path = "image_editor_gui"}